const strategyString = `{
    "id": 1,
    "title": "空頭執帶",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-belt-hold.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Belt Hold",
    "pairId": 1,
    "Counterpart": 1
  },
  {
    "id": 2,
    "title": "空方炮",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-cannon.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Cannon",
    "pairId": 2,
    "Counterpart": 1
  },
  {
    "id": 3,
    "title": "看跌反擊",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-counterattack.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Counterattack",
    "pairId": 3,
    "Counterpart": 1
  },
  {
    "id": 4,
    "title": "閨中乳燕",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-end.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish End",
    "pairId": 4,
    "Counterpart": 1
  },
  {
    "id": 5,
    "title": "熊市吞沒(穿頭破腳)",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-engulfing.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Engulfing",
    "pairId": 5,
    "Counterpart": 1
  },
  {
    "id": 6,
    "title": "空頭高浪",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-high-wave.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish High Wave",
    "pairId": 6,
    "Counterpart": 1
  },
  {
    "id": 7,
    "title": "熊市頸內線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bearish-in-neck.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish In neck",
    "pairId": 7,
    "Counterpart": 1
  },
  {
    "id": 8,
    "title": "熊市光頭光腳",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-marubozu.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Marubozu",
    "pairId": 8,
    "Counterpart": 1
  },
  {
    "id": 9,
    "title": "空頭執墊",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-mat-hold.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Mat Hold",
    "pairId": 9,
    "Counterpart": 1
  },
  {
    "id": 10,
    "title": "空頭待出線",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-on-neck.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish On Neck",
    "pairId": 10,
    "Counterpart": 1
  },
  {
    "id": 11,
    "title": "熊市紡錘線",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-spinning-top.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Spinning Top",
    "pairId": 11,
    "Counterpart": 1
  },
  {
    "id": 12,
    "title": "多頭起跑",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "bearish-start.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bearish Start",
    "pairId": 12,
    "Counterpart": 1
  },
  {
    "id": 13,
    "title": "分手",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "breakup.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Breakup",
    "pairId": 13,
    "Counterpart": 1
  },
  {
    "id": 14,
    "title": "多頭棄嬰",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-abandoned-baby.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Abandoned Baby",
    "pairId": 14,
    "Counterpart": 1
  },
  {
    "id": 15,
    "title": "多投執帶",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-belt-hold.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Belt Hold",
    "pairId": 15,
    "Counterpart": 1
  },
  {
    "id": 16,
    "title": "九天射日",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-bow-surge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Bow Surge",
    "pairId": 16,
    "Counterpart": 1
  },
  {
    "id": 17,
    "title": "多方炮",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-cannon.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Cannon",
    "pairId": 17,
    "Counterpart": 1
  },
  {
    "id": 18,
    "title": "看漲反擊",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-counterattack.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Counterattack",
    "pairId": 18,
    "Counterpart": 1
  },
  {
    "id": 19,
    "title": "直上青雲",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-doji-surge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Doji Surge",
    "pairId": 19,
    "Counterpart": 1
  },
  {
    "id": 20,
    "title": "牛市吞沒",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-engulfing.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Engulfing",
    "pairId": 20,
    "Counterpart": 1
  },
  {
    "id": 21,
    "title": "趁熱打鐵",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-escalation.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Escalation",
    "pairId": 21,
    "Counterpart": 1
  },
  {
    "id": 22,
    "title": "牛市錘線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-hammer.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Hammer",
    "pairId": 22,
    "Counterpart": 1
  },
  {
    "id": 23,
    "title": "牛市孕線(身懷六甲)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-harami.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish harami",
    "pairId": 23,
    "Counterpart": 1
  },
  {
    "id": 24,
    "title": "多頭高浪",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-high-wave.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish High Wave",
    "pairId": 24,
    "Counterpart": 1
  },
  {
    "id": 25,
    "title": "牛市頸內線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-in-neck.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish In Neck",
    "pairId": 25,
    "Counterpart": 1
  },
  {
    "id": 26,
    "title": "牛市反衝",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-kicker.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Kicker",
    "pairId": 26,
    "Counterpart": 1
  },
  {
    "id": 27,
    "title": "魚躍龍門",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-leap.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Leap",
    "pairId": 27,
    "Counterpart": 1
  },
  {
    "id": 28,
    "title": "牛市光頭光腳",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-marubozu.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Marubozu",
    "pairId": 28,
    "Counterpart": 1
  },
  {
    "id": 29,
    "title": "多頭執墊",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-mat-hold.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Mat Hold",
    "pairId": 29,
    "Counterpart": 1
  },
  {
    "id": 30,
    "title": "牛市待入線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-on-neck.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish On Neck",
    "pairId": 30,
    "Counterpart": 1
  },
  {
    "id": 31,
    "title": "牛市穿刺線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-piercing.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Piercing",
    "pairId": 31,
    "Counterpart": 1
  },
  {
    "id": 32,
    "title": "多頭三明治(多頭夾心)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-sandwich.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Sandwish",
    "pairId": 32,
    "Counterpart": 1
  },
  {
    "id": 33,
    "title": "牛市紡錘線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-spinning-top.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Spinnig Top",
    "pairId": 33,
    "Counterpart": 1
  },
  {
    "id": 34,
    "title": "多頭起跑",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-start.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Start",
    "pairId": 34,
    "Counterpart": 1
  },
  {
    "id": 35,
    "title": "內困三日翻紅",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-sudden-rebounce.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Sudden Rebounce",
    "pairId": 35,
    "Counterpart": 1
  },
  {
    "id": 36,
    "title": "東方紅(大陽升)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-surge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Surge",
    "pairId": 36,
    "Counterpart": 1
  },
  {
    "id": 37,
    "title": "彈劍長嘯",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "bullish-sword-surge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Bullish Sword Surge",
    "pairId": 37,
    "Counterpart": 1
  },
  {
    "id": 38,
    "title": "天高雲淡",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "clear-sky.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Clear Sky",
    "pairId": 38,
    "Counterpart": 1
  },
  {
    "id": 39,
    "title": "烏雲蓋頂",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "dark-cloud-cover.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Dark Cloud Cover",
    "pairId": 39,
    "Counterpart": 1
  },
  {
    "id": 40,
    "title": "曙光乍現",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "dawn-break.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Dawn Break",
    "pairId": 40,
    "Counterpart": 1
  },
  {
    "id": 41,
    "title": "旭日東昇",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "daybreak.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Daybreak",
    "pairId": 41,
    "Counterpart": 1
  },
  {
    "id": 42,
    "title": "死亡交叉",
    "strategyType": "index trend",
    "signalType": "sell",
    "illustration": "death-cross.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Death Cross",
    "pairId": 42,
    "Counterpart": 1
  },
  {
    "id": 43,
    "title": "頭頭低+底底低(朱家泓)",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "decremental-peak-trough.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Decremental Peak Trough",
    "pairId": 43,
    "Counterpart": 1
  },
  {
    "id": 44,
    "title": "步步為營",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "deliberation.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Deliberation",
    "pairId": 44,
    "Counterpart": 1
  },
  {
    "id": 45,
    "title": "定期定額",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "dollar-cost-averaging.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Dollar Cost Averaging",
    "pairId": 45,
    "Counterpart": 1
  },
  {
    "id": 46,
    "title": "雙神守門",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "double-security.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Double Security",
    "pairId": 46,
    "Counterpart": 1
  },
  {
    "id": 47,
    "title": "大雨傾盆",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "downpour.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Downpour",
    "pairId": 47,
    "Counterpart": 1
  },
  {
    "id": 48,
    "title": "下肩帶缺口",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "downside-tasuki-gap.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Downside Tasuki Gap",
    "pairId": 48,
    "Counterpart": 1
  },
  {
    "id": 49,
    "title": "天鷹開路",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "eagle-soaring.jpg",
    "userUsageRate": "",
    "publicUsageRate": "",
    "description": "",
    "englishTitle": "Eagle Soaring",
    "pairId": 49,
    "Counterpart": 1
  },
  {
    "id": 50,
    "title": "大敵當前",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "enemy-at-gate.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Enemy at Gate",
    "pairId": 50,
    "Counterpart": 1
  },
  {
    "id": 51,
    "title": "十字昏星",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "evening-doji-star.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Evening Doji Star",
    "pairId": 51,
    "Counterpart": 1
  },
  {
    "id": 52,
    "title": "一般昏星",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "evening-star.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Evening Star",
    "pairId": 52,
    "Counterpart": 1
  },
  {
    "id": 53,
    "title": "下降旗形",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "falling-flag.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Falling Flag",
    "pairId": 53,
    "Counterpart": 1
  },
  {
    "id": 54,
    "title": "下降三法",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "falling-three-methods.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Falling Three Methods",
    "pairId": 54,
    "Counterpart": 1
  },
  {
    "id": 55,
    "title": "下降三角",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "falling-triangle.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Falling Triangle",
    "pairId": 55,
    "Counterpart": 1
  },
  {
    "id": 56,
    "title": "下降楔形",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "falling-wedge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Falling Wedge",
    "pairId": 56,
    "Counterpart": 1
  },
  {
    "id": 57,
    "title": "下跌窗線",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "falling-window.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Falling Window",
    "pairId": 57,
    "Counterpart": 1
  },
  {
    "id": 58,
    "title": "背水一戰(跳空攀援線)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "gap-and-go.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Gap and Go",
    "pairId": 58,
    "Counterpart": 1
  },
  {
    "id": 59,
    "title": "黃金交叉",
    "strategyType": "index trend",
    "signalType": "buy",
    "illustration": "golden-cross.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Golden Cross",
    "pairId": 59,
    "Counterpart": 1
  },
  {
    "id": 60,
    "title": "上吊線",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "hanging-man.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Hanging Man",
    "pairId": 60,
    "Counterpart": 1
  },
  {
    "id": 61,
    "title": "頭頭高+底底高(朱家泓)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "incremental-peak-trough.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Incremental Peak Trough",
    "pairId": 61,
    "Counterpart": 1
  },
  {
    "id": 62,
    "title": "倒錘線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "inverted-hammer.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Inverted Hammer",
    "pairId": 62,
    "Counterpart": 1
  },
  {
    "id": 63,
    "title": "KD < 20",
    "strategyType": "index value",
    "signalType": "buy",
    "illustration": "kd20.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "KD < 20",
    "pairId": 63,
    "Counterpart": 1
  },
  {
    "id": 64,
    "title": "KD > 80",
    "strategyType": "index value",
    "signalType": "sell",
    "illustration": "kd80.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "KD > 80",
    "pairId": 64,
    "Counterpart": 1
  },
  {
    "id": 65,
    "title": "KDJ (隨機指標)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "kdj.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Stochastic Oscillator",
    "pairId": 90,
    "Counterpart": 1
  },
  {
    "id": 66,
    "title": "MACD > 80",
    "strategyType": "index trend",
    "signalType": "buy",
    "illustration": "macd80.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "MACD > 80",
    "pairId": 65,
    "Counterpart": 1
  },
  {
    "id": 67,
    "title": "十字晨星",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "morning-doji-star.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Morning Doji Star",
    "pairId": 66,
    "Counterpart": 1
  },
  {
    "id": 68,
    "title": "一般晨星",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "morning-star.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Morning Star",
    "pairId": 67,
    "Counterpart": 1
  },
  {
    "id": 69,
    "title": "疊疊空方炮",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "multiple-bearish-cannon.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Multiple Bearish Cannon",
    "pairId": 68,
    "Counterpart": 1
  },
  {
    "id": 70,
    "title": "疊疊多方炮",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "multiple-bullish-cannon.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Multiple Bullish Cannon",
    "pairId": 69,
    "Counterpart": 1
  },
  {
    "id": 71,
    "title": "好友反攻",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "nightfall.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Night Fall",
    "pairId": 70,
    "Counterpart": 1
  },
  {
    "id": 72,
    "title": "能量潮升",
    "strategyType": "index trend",
    "signalType": "buy",
    "illustration": "obv-after-deficit.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "OBV after deficit",
    "pairId": 71,
    "Counterpart": 1
  },
  {
    "id": 73,
    "title": "能量潮落",
    "strategyType": "index trend",
    "signalType": "sell",
    "illustration": "obv-after-surplus.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "OBV after surplus",
    "pairId": 72,
    "Counterpart": 1
  },
  {
    "id": 74,
    "title": "高檔鈍化 (KD)",
    "strategyType": "index trend",
    "signalType": "buy",
    "illustration": "overbought-kd.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Overbought (KD)",
    "pairId": 73,
    "Counterpart": 1
  },
  {
    "id": 75,
    "title": "高檔鈍化 (RSI)",
    "strategyType": "index trend",
    "signalType": "buy",
    "illustration": "overbought-rsi.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Overbought RSI",
    "pairId": 74,
    "Counterpart": 1
  },
  {
    "id": 76,
    "title": "低檔鈍化 (KD)",
    "strategyType": "index trend",
    "signalType": "sell",
    "illustration": "oversold-kd.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Oversold (KD)",
    "pairId": 75,
    "Counterpart": 1
  },
  {
    "id": 77,
    "title": "低檔鈍化 (RSI)",
    "strategyType": "index trend",
    "signalType": "sell",
    "illustration": "oversold-rsi.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Oversold RSI",
    "pairId": 76,
    "Counterpart": 1
  },
  {
    "id": 78,
    "title": "獨特三河床",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "rebouncing-stream-bed.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rebouncing Stream Bed",
    "pairId": 78,
    "Counterpart": 1
  },
  {
    "id": 79,
    "title": "倒V形反轉",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "reversed-v-shaped-rebound.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Reversed V-Shaped",
    "pairId": 79,
    "Counterpart": 1
  },
  {
    "id": 80,
    "title": "芝麻開花(二次高開陽線)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rise-in-tiers.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rise In Tiers",
    "pairId": 80,
    "Counterpart": 1
  },
  {
    "id": 81,
    "title": "上升旗形",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rising-flag.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rising Flag",
    "pairId": 81,
    "Counterpart": 1
  },
  {
    "id": 82,
    "title": "上升三法",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rising-three-methods.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rising Three Methods",
    "pairId": 82,
    "Counterpart": 1
  },
  {
    "id": 83,
    "title": "上升三角",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rising-triangle.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rising Triangle",
    "pairId": 83,
    "Counterpart": 1
  },
  {
    "id": 84,
    "title": "上升楔形",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rising-wedge.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rising Wedge",
    "pairId": 84,
    "Counterpart": 1
  },
  {
    "id": 85,
    "title": "上漲窗線",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "rising-window.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rising Window",
    "pairId": 85,
    "Counterpart": 1
  },
  {
    "id": 86,
    "title": "ROC (變化率)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "roc.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Rate of Change",
    "pairId": 77,
    "Counterpart": 1
  },
  {
    "id": 87,
    "title": "RSI < 20",
    "strategyType": "index value",
    "signalType": "buy",
    "illustration": "rsi20.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "RSI < 20",
    "pairId": 86,
    "Counterpart": 1
  },
  {
    "id": 88,
    "title": "RSI > 80",
    "strategyType": "index value",
    "signalType": "sell",
    "illustration": "rsi80.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "RSI > 80",
    "pairId": 87,
    "Counterpart": 1
  },
  {
    "id": 89,
    "title": "南方三星",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "southern-three-stars.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Southern Three Stars",
    "pairId": 88,
    "Counterpart": 1
  },
  {
    "id": 90,
    "title": "仙人指路",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "steady-guidance.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Steady Guidance",
    "pairId": 89,
    "Counterpart": 1
  },
  {
    "id": 91,
    "title": "百分比停利",
    "strategyType": "stop loss",
    "signalType": "sell",
    "illustration": "stop-gain-by-percentage.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Stop Gain By Percentage",
    "pairId": 91,
    "Counterpart": 1
  },
  {
    "id": 92,
    "title": "百分比停損",
    "strategyType": "stop loss",
    "signalType": "sell",
    "illustration": "stop-loss-by-percentage.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Stop Loss By Percentage",
    "pairId": 92,
    "Counterpart": 1
  },
  {
    "id": 93,
    "title": "飛燕歸巢",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "swallow-homing.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Swallow Homing",
    "pairId": 93,
    "Counterpart": 1
  },
  {
    "id": 94,
    "title": "鷹撲",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "swoop.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Swoop",
    "pairId": 94,
    "Counterpart": 1
  },
  {
    "id": 95,
    "title": "三隻烏鴉",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "three-black-crows.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three Black Crows",
    "pairId": 95,
    "Counterpart": 1
  },
  {
    "id": 96,
    "title": "三連陽買入法",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "three-consecutive-rising.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three Consecutive Rising",
    "pairId": 96,
    "Counterpart": 1
  },
  {
    "id": 97,
    "title": "一陽穿三線(三線反擊)",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "three-lined-counterattack.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three-Lined Counterattack",
    "pairId": 100,
    "Counterpart": 1
  },
  {
    "id": 98,
    "title": "三外部下跌",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "three-outside-down.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three Outside Down",
    "pairId": 97,
    "Counterpart": 1
  },
  {
    "id": 99,
    "title": "三外部上漲",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "three-outside-up.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three Outside Up",
    "pairId": 98,
    "Counterpart": 1
  },
  {
    "id": 100,
    "title": "白色三兵",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "three-white-soldiers.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Three White Soldiers",
    "pairId": 99,
    "Counterpart": 1
  },
  {
    "id": 101,
    "title": "移動停損",
    "strategyType": "stop loss",
    "signalType": "sell",
    "illustration": "trailing-stop.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Trailing Stop",
    "pairId": 101,
    "Counterpart": 1
  },
  {
    "id": 102,
    "title": "約會",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "tryst.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Tryst",
    "pairId": 102,
    "Counterpart": 1
  },
  {
    "id": 103,
    "title": "鑷底",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "tweezer-bottom.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Tweezer Bottom",
    "pairId": 103,
    "Counterpart": 1
  },
  {
    "id": 104,
    "title": "鑷頂",
    "strategyType": "candlestick pattern",
    "signalType": "sell",
    "illustration": "tweezer-top.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Tweezer Top",
    "pairId": 104,
    "Counterpart": 1
  },
  {
    "id": 105,
    "title": "雙鴉躍空",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "upside-gap-two-crows.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Upside Gap Two Crows",
    "pairId": 105,
    "Counterpart": 1
  },
  {
    "id": 106,
    "title": "上肩帶缺口",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "upside-tasuki-gap.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "Upside Tasuki Gap",
    "pairId": 106,
    "Counterpart": 1
  },
  {
    "id": 107,
    "title": "V形反轉",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "v-shaped-rebound.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "V-Shaped Rebound",
    "pairId": 107,
    "Counterpart": 1
  },
  {
    "id": 108,
    "title": "威廉震盪指標",
    "strategyType": "candlestick pattern",
    "signalType": "buy",
    "illustration": "william-r.jpg",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "William %R",
    "pairId": 108,
    "Counterpart": 1
  },
  {
    "id": "",
    "title": "",
    "strategyType": "",
    "signalType": "",
    "illustration": "",
    "userUsageRate": 50,
    "publicUsageRate": 50,
    "description": "golden cross is ...",
    "englishTitle": "",
    "pairId": "",
    "Counterpart": ""
  }`

const strategyJSONArray = strategyString.split('},')
const strategyArray = []
for (let i = 0; i < strategyJSONArray.length-1; i++) {

  strategyJSONArray[i] = strategyJSONArray[i] + "}"
  strategyArray.push(JSON.parse(strategyJSONArray[i]))
}
strategyArray.push(JSON.parse(strategyJSONArray[strategyJSONArray.length-1]))

const convertToExample = (object:any) => {
  // console.log()
  const newObject = {
    name: object.title,
    id: object.id,
    image: `../assets/strategy-illustrations/${object.illustration}`,
    types: [
      {
        normal: {
          image: "/react-stockmate-e2/static/media/normal.461bd7373ca90faa99a317a27dfa80d8.svg",
          strength: [],
          weakness: [
            "rock",
            "ghost",
            "steel"
          ],
          resistance: [
            "ghost"
                ],
          vulnerable: [
                  "fighting"
                ]
              }
            },
            {
              flying: {
                image: "/react-stockmate-e2/static/media/flying.d2c03053c64617359912.png",
                strength: [
                  "fighting",
                  "bug",
                  "grass"
                ],
                weakness: [
                  "rock",
                  "steel",
                  "electric"
                ],
                resistance: [
                  "fighting",
                  "ground",
                  "bug",
                  "grass"
                ],
                vulnerable: [
                  "rock",
                  "electric",
                    "ice"
                  ]
                }
              }
            ]
          }
          // console.log(newObject)
          return newObject 
        }
        
        const exampleFormat = {
          "name": "pidgeot",
          "id": 18,
          "image": "/react-stockmate-e2/static/media/18.0fa9103ab26eab46c389.png",
          "types": [
            {
              "normal": {
                "image": "/react-stockmate-e2/static/media/normal.461bd7373ca90faa99a317a27dfa80d8.svg",
                "strength": [],
                "weakness": [
                  "rock",
                    "ghost",
                    "steel"
                  ],
                  "resistance": [
                    "ghost"
                  ],
                  "vulnerable": [
                    "fighting"
                  ]
                }
              },
              {
                "flying": {
                  "image": "/react-stockmate-e2/static/media/flying.d2c03053c64617359912.png",
                  "strength": [
                    "fighting",
                    "bug",
                    "grass"
                  ],
                  "weakness": [
                    "rock",
                    "steel",
                    "electric"
                  ],
                  "resistance": [
                    "fighting",
                    "ground",
                    "bug",
                    "grass"
                  ],
                  "vulnerable": [
                    "rock",
                    "electric",
                    "ice"
                  ]
                }
              }
            ]
          }
export const strategyObject = strategyArray.map((strategy)=>{
  return convertToExample(strategy)
})